catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('borrowed/', views.all_borrowed_books, name='all-borrowed'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from .constants import MAX_LENGTH_NAME, MAX_LENGTH_AUTHOR_NAME, MAX_LENGTH_SUMMARY, MAX_LENGTH_ISBN
from django.contrib.auth.models import User
from datetime import date
from django.conf import settings

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=MAX_LENGTH_NAME,
        help_text='Enter a book genre (e.g. Science Fiction)'
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Language(models.Model):
    """Model representing a language"""
    name = models.CharField(max_length=MAX_LENGTH_NAME, help_text="Enter the book's natural language")

    def __str__(self):
        """String for representing the Model object."""
        return self.name

class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=MAX_LENGTH_NAME)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=MAX_LENGTH_SUMMARY, help_text='Enter a brief description of the book')
    isbn = models.CharField(
        'ISBN',
        max_length=MAX_LENGTH_ISBN,
        unique=True,
        help_text='13 Character ISBN number'
    )
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='Unique ID for this particular book across whole library'
    )
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=MAX_LENGTH_NAME)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        return bool(self.due_back and date.today() > self.due_back)

class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=MAX_LENGTH_AUTHOR_NAME)
    last_name = models.CharField(max_length=MAX_LENGTH_AUTHOR_NAME)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm
from catalog.models import BookInstance

class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
       data = self.cleaned_data['due_back']
       if data < datetime.date.today():
           raise ValidationError(_('Invalid date - renewal in past'))
       if data > datetime.date.today() + datetime.timedelta(weeks=4):
           raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
       return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views.py
from django.shortcuts import render, get_object_or_404
from catalog.models import Book, Author, BookInstance, Genre
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from catalog.forms import RenewBookModelForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
import datetime
from catalog.constants import (
    DEFAULT_PAGINATE_BY,
    BOOKINSTANCE_STATUS_AVAILABLE,
    BOOKINSTANCE_STATUS_MAINTENANCE,
    BOOKINSTANCE_STATUS_ON_LOAN,
    BOOKINSTANCE_STATUS_RESERVED,
)

# Create your views here.
class BookListView(generic.ListView):
    model = Book
    paginate_by = DEFAULT_PAGINATE_BY
    
class BookDetailView(generic.DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['bookinstances'] = self.object.bookinstance_set.all()
        from catalog.models import BookInstance
        context['status_choices'] = dict(BookInstance.LOAN_STATUS)
        context['STATUS_AVAILABLE'] = BOOKINSTANCE_STATUS_AVAILABLE
        context['STATUS_MAINTENANCE'] = BOOKINSTANCE_STATUS_MAINTENANCE
        context['STATUS_ON_LOAN'] = BOOKINSTANCE_STATUS_ON_LOAN
        context['STATUS_RESERVED'] = BOOKINSTANCE_STATUS_RESERVED
        return context

def book_detail_view(request, primary_key):
    book = get_object_or_404(Book, pk=primary_key)
    bookinstances = book.bookinstance_set.all()
    from catalog.models import BookInstance
    status_choices = dict(BookInstance.LOAN_STATUS)
    return render(request, 'catalog/book_detail.html', context={
        'book': book,
        'bookinstances': bookinstances,
        'status_choices': status_choices,
        'STATUS_AVAILABLE': BOOKINSTANCE_STATUS_AVAILABLE,
        'STATUS_MAINTENANCE': BOOKINSTANCE_STATUS_MAINTENANCE,
        'STATUS_ON_LOAN': BOOKINSTANCE_STATUS_ON_LOAN,
        'STATUS_RESERVED': BOOKINSTANCE_STATUS_RESERVED,
    })

def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_instances_available = BookInstance.objects.filter(status__exact=BookInstance.LOAN_STATUS[2][0]).count()
    num_authors = Author.objects.count()
    num_visits = request.session.get('num_visits', 0) + 1
    request.session['num_visits'] = num_visits

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }
    
    return render(request, 'index.html', context=context)

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = DEFAULT_PAGINATE_BY

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact=BOOKINSTANCE_STATUS_ON_LOAN)
            .order_by('due_back')
        )
@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        form = RenewBookModelForm(request.POST)
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return HttpResponseRedirect(reverse('all-borrowed'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={'renewal_date': proposed_renewal_date})
    context = {
        'form': form,
        'book_instance': book_instance,
    }
    return render(request, 'catalog/book_renew_librarian.html', context)

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def all_borrowed_books(request):
    bookinstance_list = BookInstance.objects.filter(status=BOOKINSTANCE_STATUS_ON_LOAN).order_by('due_back')
    context = {'bookinstance_list': bookinstance_list}
    return render(request, 'catalog/all_borrowed_books.html', context)

class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/11/2023'}
    permission_required = 'catalog.add_author'

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    permission_required = 'catalog.change_author'

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    permission_required = 'catalog.delete_author'

    def form_valid(self, form):
        try:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        except Exception as e:
            return HttpResponseRedirect(
                reverse("author-delete", kwargs={"pk": self.object.pk})
            )

class AuthorDetailView(generic.DetailView):
    model = Author

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = DEFAULT_PAGINATE_BY

catalog/templates/catalog/all_borrowed_books.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
    <h2> {% trans "All Borrowed Books" %}</h2>
    {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
          <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %}{% if perms.catalog.can_mark_returned %} - <a href="{% url 'renew-book-librarian' bookinst.id %}">{% trans "Renew" %}</a>{% endif %}
        </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>{% trans "There are no books borrowed." %}</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
{% load i18n %}
<h1>{% trans "Delete Author" %}: {{ author }}</h1>
{% if author.book_set.all %}
    <p>{% trans "You can't delete this author until all their books have been deleted:" %} </p>
    <ul>
        {% for book in author.book_set.all %}
            <li><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</li>
        {% endfor %}
    </ul>
{% else %}
    <p>{% trans "Are you sure you want to delete the author" %}: {{ author }}?</p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" action="" value="Yes, delete.">
    </form>
{% endif %}
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
    <h2> {% trans "Author" %}: {{ author.last_name }}, {{ author.first_name }}</h2>
    <p>{{ author.date_of_birth|date:"d/m/Y" }} - {{ author.date_of_death|date:"d/m/Y" }}</p>
    <h3>{% trans "Books" %}:</h3>
    {% if author.book_set.all %}
        <p>
            {% for book in author.book_set.all %}
                {{ book.title }}{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
    {% else %}
        <p>{% trans "No books available." %}</p>
    {% endif %}
{% endblock %}

{% block sidebar %}
  {{ block.super }}
  {% if perms.catalog.change_author or perms.catalog.delete_author %}
  <hr>
  <ul class="sidebar-nav">
    {% if perms.catalog.change_author %}
      <li><a href="{% url 'author-update' author.id %}">{% trans "Update author" %}</a></li>
    {% endif %}
    {% if not author.book_set.all and perms.catalog.delete_author %}
      <li><a href="{% url 'author-delete' author.id %}">{% trans "Delete author" %}</a></li>
    {% endif %}
    </ul>
  {% endif %}
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" />
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
  <h2>{% trans "All Authors" %}</h2>
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{% url 'author-detail' author.pk %}">
          {{ author.last_name }}, {{ author.first_name }}
        </a>
      </li>
    {% empty %}
      <li>{% trans "No authors available." %}</li>
    {% endfor %}
  </ul>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Title:" %} {{ book.title }}</h1>

    <p><strong>{% trans "Author:" %}</strong> <a href="">{{ book.author }}</a> </p>
    <p><strong>{% trans "Summary:" %}</strong> {{ book.summary }}</p>
    <p><strong>{% trans "ISBN:" %}</strong> {{ book.isbn }}</p>
    <p><strong>{% trans "Language:" %}</strong> {{ book.language }}</p>
    <p><strong>{% trans "Genre:" %}</strong> {{ book.genre.all|join:", " }}</p>
    <div class="book-detail-indent">
        <h4>{% trans "Copies" %}</h4>

        {% for copy in bookinstances %}
            <hr>
            <p class="{% if copy.status == STATUS_AVAILABLE %}text-success{% elif copy.status == STATUS_MAINTENANCE %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != STATUS_AVAILABLE %}
                <p><strong>{% trans "Due to be returned:" %}</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>{% trans "Imprint:" %}</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>{% trans "Id:" %}</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "Book List" %}</h1>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>{% trans "There are no books in the library." %}</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
  <h1>{% trans "Renew:" %} {{ book_instance.book.title }}</h1>
  <p><strong>{% trans "Borrower:" %}</strong> {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>{% trans "Due date" %}: {{ book_instance.due_back }}</p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Borrowed books" %}</h1>
    {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>{% trans "There are no books borrowed." %}</p>
    {% endif %}
{% endblock %}